[package]
name = "rpc-error-convert"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
rpc = { workspace = true }

serde_json = { workspace = true }
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
