// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Util$Type } from "./Util";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Util"]: Util$Type;
    ["contracts/rollup2/base/Util.sol:Util"]: Util$Type;
  }
}
