// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RollupV7$Type } from "./RollupV7";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RollupV7"]: RollupV7$Type;
    ["contracts/rollup/RollupV7.sol:RollupV7"]: RollupV7$Type;
  }
}
